version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app:cached
    command: sleep infinity
    depends_on:
      - db
  db:
    image: postgres:14-alpine3.15
    restart: unless-stopped
    volumes:
      - qjumper-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Django1234
      POSTGRES_DB: aries

volumes:
  qjumper-postgres-data: